name: ci-windows

on:
  push:
  pull_request:
    branches:
      - master
      - dev

# TODO: replace hard-coded if statements for msvc-CMake configuration
jobs:
  build-msvc:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, windows-2019, windows-2022]
        build-type: [Release, Debug]
        cmake-version: [3.16.x,
                        3.23.x]

    name: "Build: ${{matrix.os}} • ${{matrix.build-type}} • ${{matrix.cmake-version}} • MSVC"
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2

    - name: Update CMake
      uses: jwlawson/actions-setup-cmake@v1.10
      with:
        cmake-version: ${{matrix.cmake-version}}

    # Configure for msvc-17
    - name: Setup examples, configure, and run them (${{matrix.os}})
      if: ${{matrix.os == "windows-2022"}}
      env:
        CMAKE_GENERATOR: "Visual Studio 17 2022"
      run: .\scripts\run_examples.bat ${{matrix.build-type}}

    # Configure for msvc-16
    - name: Setup examples, configure, and run them (${{matrix.os}})
      if: ${{matrix.os == "windows-2019"}}
      env:
        CMAKE_GENERATOR: "Visual Studio 16 2019"
      run: .\scripts\run_examples.bat ${{matrix.build-type}}

    # Configure for msvc-15
    - name: Setup examples, configure, and run them (${{matrix.os}})
      if: ${{matrix.os == "windows-2016"}}
      env:
        CMAKE_GENERATOR: "Visual Studio 15 2017"
      run: .\scripts\run_examples.bat ${{matrix.build-type}}
